### ISSUE TITLE
Text at saving screen is distorted

### ISSUE THREAD

**Issue by Kodden585** [VariantXYZ/medarot1#155]
The text that displays while saving is distorted, this happens both on emulation and on real hardware, at least on the Gameboy Color.
![Medarot - Kuwagata Version (Japan) (t v0 4 1)-0](https://user-images.githubusercontent.com/62814230/88569399-ac8fb080-d03a-11ea-8484-e7d251329d5a.png)

**Comment by VariantXYZ** [comment]
Regression, fixed by 8b5918d234673e558db37fdbdff78a089fb16e2e.
