### ISSUE TITLE
Import shop replaces world tile with textbox tile

### ISSUE THREAD

**Issue by jul-reb** [VariantXYZ/medarot1#171]
![image](https://user-images.githubusercontent.com/42237358/96138944-950be980-0efe-11eb-88a9-95f8c671c917.png)

Steps to reproduce:
1. go to the import shop in the shopping district (top right of the area)
2. talk to cashier, examine all the head parts, press select to get extra text
3. cancel out of the menu, the potted plant will have a glitched texture

Not that important, but the principle behind this could cause bigger errors.
Attached is a mGBA savestate.
[bug.zip](https://github.com/VariantXYZ/medarot1/files/5385322/bug.zip)
Note that the savestates for this emulator can be opened as image files, it is actually a savegame, not just a screenshot.

**Comment by VariantXYZ** [comment]
https://2572-66696472-gh.circle-artifacts.com/0/patch/m1kabuto-988-f7e192ea77e5c475747366d61418727a202ce9ff.ips
